### ISSUE TITLE
Does not work with setuptools_scm v6.1.0 — AttributeError: 'NoneType' object has no attribute 'version_cls'

### ISSUE THREAD

**Issue by sbraz** [Changaco/setuptools_scm_git_archive#19]
Hi,
Although I also reported this as https://github.com/pypa/setuptools_scm/issues/615, I thought it would be worth mentioning here that `setuptools_scm_git_archive` doesn't work with `setuptools_scm` v6.1.0 (since https://github.com/pypa/setuptools_scm/commit/fbadf5b060cdd7ec1fb3d29d885868b7b756497c to be exact).

The failure looks like this:
```
/usr/local/lib/python3.9/site-packages/setuptools_scm/version.py:212: UserWarning: meta invoked without explicit configuration, will use defaults where required.
  warnings.warn(
Traceback (most recent call last):
  File "/pikepdf-2.16.1/setup.py", line 38, in <module>
    __version__ = get_version()
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 170, in get_version
    return _get_version(config)
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 174, in _get_version
    parsed_version = _do_parse(config)
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 127, in _do_parse
    version = _version_from_entrypoints(config) or _version_from_entrypoints(
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 65, in _version_from_entrypoints
    version = _call_entrypoint_fn(root, config, ep.load())
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 54, in _call_entrypoint_fn
    return fn(root)
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm_git_archive/__init__.py", line 21, in parse
    return archival_to_version(data)
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm_git_archive/__init__.py", line 15, in archival_to_version
    return meta(versions[0])
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/version.py", line 216, in meta
    parsed_version = _parse_tag(tag, preformatted, config)
  File "/usr/local/lib/python3.9/site-packages/setuptools_scm/version.py", line 195, in _parse_tag
    version_cls = config.version_cls or VERSION_CLASS
AttributeError: 'NoneType' object has no attribute 'version_cls'
```

Reproducer Dockerfile:
```Dockerfile
FROM python:3.9
RUN wget -nv https://github.com/pikepdf/pikepdf/archive/v2.16.1.tar.gz
RUN tar xf v2.16.1.tar.gz
WORKDIR pikepdf-2.16.1

RUN pip3 install setuptools_scm_git_archive
# Bad 
RUN pip3 install git+https://github.com/pypa/setuptools_scm@fbadf5b060cdd7ec1fb3d29d885868b7b756497c

# The parent commit was still good
#RUN pip3 install git+https://github.com/pypa/setuptools_scm@b8451688b9cb295136c0154c7c59c25a9d88f844

RUN python setup.py --version
```

**Comment by RonnyPfannschmidt** [comment]
extra note - the breaking release has been yanked for other reasons

the bug is triggered due to not tracking backward compatibility for the hook invocations as setuptools_scm itself uses the new config based api since quite a while now, however the mistake has not been caught due to not using type annotations yet

**Comment by toralf** [comment]
happened still with -6.3.0 : https://bugs.gentoo.org/811573

**Comment by RonnyPfannschmidt** [comment]
Tag regex looks like a new error, more information needed

**Comment by sbraz** [comment]
@RonnyPfannschmidt  this can easily be reproduced with:
```Dockerfile
FROM python:3.9
RUN wget -nv https://github.com/pikepdf/pikepdf/archive/v2.16.1.tar.gz
RUN tar xf v2.16.1.tar.gz
WORKDIR pikepdf-2.16.1

RUN pip3 install setuptools_scm_git_archive

RUN python setup.py --version
```

**Comment by sbraz** [comment]
setupsools_scm 6.3.2 fixed this, the issue can be closed.
